version: '3'
services:
  db:
    image: postgres
    volumes: 
      - ./data/pg-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 8500:5432
  web:
    build: .
    volumes: 
      - .:/workspace
    ports:
      - 3000:3000
    depends_on:
      - db

