# This is a basic workflow to help you get started with Actions

name: Unit Tests check

on:
  push:
    branches: [ master, staging, dev ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run npm test on all projects 
        run: npm test

